version: '3'

services:
  mongo:
    image: mongo:latest
    command: mongod --storageEngine wiredTiger
    ports:
      - "27017:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: default
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: django_db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: default
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
  web:
    image: app
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    links:
      - mongo
    depends_on:
      - mongo